services:
  server:
    build:
      context: .
      target: development
    image: ${COMPOSE_PROJECT_NAME}-dev
    volumes:
      # Mount local source code for hot-reloading
      - .:/usr/src/app
      # Anonymize node_modules to use the container's version
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  database:
    ports:
      # Expose database port to the host machine for local tools
      - '${DATABASE_PORT:-5432}:5432'

  db-admin:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - '8080:8080'
    networks:
      - private-net
      - public-net
    depends_on:
      - database
